### ISSUE TITLE
Race Condition?  Reload loop?

### ISSUE THREAD

**Issue by furicle** [pmario/file-backups#13]
Hard to describe, please see this video from my phone.  Any attempts to record it using the computer itself stopped the condition.

I can't pin down what steps cause it to happen - and usually once you stop it (as shown in the video) it doesn't come back.

https://www.dropbox.com/s/798dhgfo8lmc147/File%202017-11-22%2C%2010%2002%2003%20AM.mov?dl=0

**Comment by pmario** [comment]
That's strange. .. But I know symptoms like this. It seems to be a problem with the scroll bars, that browser sometimes wan to show. As they arerendered the content is changed, because the scroll bars need some space for them selfs. .. But this new rendering causes the bars to disapear ... Or vice versa. ... I'll have a look at the CSS settigs. ....

**Comment by pmario** [comment]
Is this still an issue?

**Comment by furicle** [comment]
Can not reproduce - I'd kill this issue
