### ISSUE TITLE
Barely working with FF69.0.2

### ISSUE THREAD

**Issue by Coburn** [pmario/file-backups#30]
I'm using PVHL's [Woas](https://github.com/PVHL/woas) project and File Backups does not save the file unless I open Preferences, save the preferences, and reload the page. Even then it doesn't always work. Having the same behavior with [SaveTiddlers](https://github.com/buggyj/savetiddlers).

**Comment by pmario** [comment]
Hi, .... Hmmm I have no idea what Woas is or means. ... What makes you think, that a TiddlyWiki extension should work with it?

**Comment by pmario** [comment]
I did download a woas 0.13.0 beta 1..  It looks like it is based on an ancient TWclassic saver. ... 

It seems there is a TiddlyWiki signature left in the code, that let's the extension "think" it could patch the existing saver. ... The problem is ... it can't, since the used saver was modified in a way, that seems to be not compatible.

**Comment by pmario** [comment]
Is there a community behind the system, or is it just you, who is still using it. .... Every link, that I found seems to point to an abandoned system.

**Comment by Coburn** [comment]
I'm aware of one dev still active, is all. I am trying to get it working
after several years of not using it, because there are still these saver
files out there. I will ask someone else if the saver can be adapted.
Thanks.

**Comment by pmario** [comment]
you can try to port the content to tiddlywiki.com
